In [3]:
import numpy as np

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [12]:
#lista normal em python
lis = [(1,2,3,4),(5,6,7,8,)]
#vetor ou matriz com o numpy
x=np.array(lis) 
type(x)
x.ndim
x.shape

(2, 4)

In [13]:
#Para saber a dimensão e número de linhas e colunas. No caso de uma dimensão, 
#o número de caracteres
A = x.ndim
B = x.shape

In [15]:
print('Resulting matrix:\n\n',x,'\n\nDimensions:',A,
'\nshape (rows,columns):',B)

Resulting matrix:

 [[1 2 3 4]
 [5 6 7 8]] 

Dimensions: 2 
shape (rows,columns): (2, 4)


In [18]:
#Fazer a transposta de uma matriz
t_x = x.transpose()
t_x
C = t_x.ndim
D = t_x.shape
print("Resulting matrix:\n\n",t_x,"\n\nDimensions:",C,"Shape (rown, columns):",D)

Resulting matrix:

 [[1 5]
 [2 6]
 [3 7]
 [4 8]] 

Dimensions: 2 Shape (rown, columns): (4, 2)


In [34]:
#criando array com a função arange(). Não define o tipo de elemento.
np.arange(10)
pares_array=np.arange(0,12,2)
pares_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10])

In [23]:
#usando o comando dtype definimos o tipo do número
pares_array2=np.arange(0,12,2,dtype=float)
pares_array2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [36]:
#retorna um array uniformemente espaçado em um intervalo definido

y=np.linspace(0,5,5)#5 números com intervalos de 5 entre eles de 0 a 5
z=np.linspace(51,100, dtype=int)#quando não definido o espaçamento, o default é 50
print('Here are the arrays:\n\n','y=',y,'\n\nz=',z)

Here are the arrays:

 y= [0.   1.25 2.5  3.75 5.  ] 

z= [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [8]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#para criar matrizes de zero, um ou identidade
np.zeros(3)
np.zeros((3,3),dtype=int)
np.ones(5)
np.ones((2,6), dtype=int)
np.eye(2)#obviamente, sempre será uma matriz quadrada

# Os valores passados como parâmetro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))
d

array([0., 0., 0.])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

array([1., 1., 1., 1., 1.])

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

array([[1., 0.],
       [0., 1.]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [6]:
#Treŝ funções para gerar números aleatórios
#comando rand() gera númeors aleatórios entre 0 e 1
#comando randn() gera númeors aleatórios com distribuição normal ou Gaussiana
#comando randint gera númeors aleatórios inteiros detro de um intervalo definido

np.random.rand(5)
np.random.rand(2,3)
np.random.randn(5)
np.random.randn(2,3)

#Syntax: np.random,randint(lower value, higher value, number of values)
np.random.randint(1,5)
np.random.randint(1,100,8)
np.random.randint(1,100,(2,3))#para gerar uma matriz


array([0.06804854, 0.33464227, 0.21810895, 0.87462038, 0.74608505])

array([[0.07185203, 0.08148535, 0.32774432],
       [0.54125976, 0.37305103, 0.10768282]])

array([-1.16688013, -0.80554966, -1.19695296,  0.7981727 , -1.9535314 ])

array([[ 0.18728154,  1.51969412,  1.36172421],
       [ 0.8342141 , -0.12601766, -0.66913711]])

1

array([57, 16, 92, 71, 69, 83, 76, 26])

array([[42, 73, 55],
       [67, 60, 83]])

# **MANIPULATION ARRAYS**

In [8]:
#Função reshape() altera a dimensionalidade do array

freq=np.arange(10)
value=np.random.randn(10)
freq
value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([-0.37558786, -0.50317731, -0.30591593, -0.29731434, -0.87323963,
       -0.4178281 , -2.10142008,  0.15476333, -0.53551359,  1.69241014])

In [18]:
np.reshape(freq,(2,5))
np.reshape(value,(5,2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[-0.37558786, -0.50317731],
       [-0.30591593, -0.29731434],
       [-0.87323963, -0.4178281 ],
       [-2.10142008,  0.15476333],
       [-0.53551359,  1.69241014]])

In [27]:
#encontrar máx(), min(), argumento do máx e min

#duas maneiras
value.max()
max(value)
min(freq)
freq.min()
#apenas uma maneira para os argumentos, lembrando que começa a contar de 0
value.argmax()
freq.argmin()

1.6924101384767904

1.6924101384767904

0

0

9

0

In [32]:
A = value.max();B = value.min();
C = value.argmax(); D = value.argmin()

print('Maximum value: {}\nMinimum Value: {}\
\nItem {} is the maximum value, while item {}\
 is the minimum value'.format(A,B,C,D))

Maximum value: 1.6924101384767904
Minimum Value: -2.101420077256655
Item 9 is the maximum value, while item 6 is the minimum value


In [5]:
# soma de maneira acumulativa os elementos de um array
vetor1 = np.array([0,1,2,3,4,5,6,7,8,9])
vetor1
vetor1.cumsum()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [9]:
#manipulando matrizes
matrix = np.array(([5,10,15],[20,25,30],[35,40,45]))
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
#Slice matriz 
#apenas linha
matrix_column = matrix[0]
matrix_column

#apenas coluna
#o primeiro termo, antes da vírgula, define a linha e o segundo a coluna
matrix_column = matrix[0:,0]
matrix_column

#para imprimir em forma de coluna precisa definir um range
matrix_column = matrix[0:,0:1]
matrix_column

#segunda coluna.
#como tem valores em todas das linhas pode usar apenas : no lugar dp zero
matrix_column = matrix[:,1:2]
matrix_column

array([ 5, 10, 15])

array([ 5, 20, 35])

array([[ 5],
       [20],
       [35]])

array([[10],
       [25],
       [40]])

In [11]:
grande_array = np.arange(0,100,2).reshape(5,10)
grande_array

#fatiando uma matriz
column_array = grande_array[:3,-4:]
column_array

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

array([[12, 14, 16, 18],
       [32, 34, 36, 38],
       [52, 54, 56, 58]])

#**INDEXING AND SELECTING ARRAY**

In [14]:
# Usando o método around - arredondar os números
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
b

array([1., 2., 2., 2., 4., 4.])

In [17]:
# Copiando um array
C = b.flatten()

C

array([1., 2., 2., 2., 4., 4.])

In [5]:
#caso o slice de um array seja atribuido a outra variável e esta seja alterada
#o array original também é alterado. Não ocorre o mesmo em listas
array1 = np.arange(11)
array1

#nova variável para armazenar uma fatia do array
array1_slice = array1[:4]

#atribuição de novos valores a variável
array1_slice[:]= [89,63,57,369]
array1_slice

#o array original é alterado com os valores da variável array1_slice
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 89,  63,  57, 369])

array([ 89,  63,  57, 369,   4,   5,   6,   7,   8,   9,  10])

# ***Condicionais em array***

In [6]:
odd_array = np.arange(0,100,8)
odd_array
#forma estendida, mas retornar True ou False
bool_array=odd_array>11
bool_array
estendida = odd_array[bool_array]
estendida
#forma compacta para retornar apenas os valores maiores que 11
compact = odd_array[odd_array>11]
compact

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

array([16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])

array([16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])

In [12]:
#criando uma matriz a partir dos valores maiores que 80 do grande_array
grande_array>80
novo_array = grande_array[grande_array>80].reshape(3,3)
novo_array

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

array([[82, 84, 86],
       [88, 90, 92],
       [94, 96, 98]])

# **Algumas funções universais com array**

In [13]:
new_array = np.arange(11)
new_array
sc=100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#adição com escalar
add_array=np.add(new_array,sc)
add_array

#subtração de array
sub_array=np.subtract(add_array,new_array)
sub_array

#logaritmo - a mensagem de erro é proposital para mostrar que dividindo por zero 
#aparece uma mensagem de erro, mas as demais operações sõ
log_array = np.log(new_array)
log_array

#seno
sen_array=np.sin(new_array)
sen_array

#cosseno
cos_array=np.cos(new_array)
cos_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

/home/wellington/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in log
  # Remove the CWD from sys.path while we load stuff.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])